// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xutmgzmorqhssbrlarva.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1dG1nem1vcnFoc3NicmxhcnZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNjY5ODYsImV4cCI6MjA2MjY0Mjk4Nn0.jaOogyLl1pqk5Y7WWV0xjL7DZADEFzxUb_AlPD5_Z40";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);